basePath: /api/private/
host: api-service.logangodsey.com
info:
  contact:
    email: logan@logangodsey.com
    name: API Support
  description: These APIs handle a lot of backend things..
  termsOfService: http://swagger.io/terms/
  title: Logan's API
  version: "1.0"
paths:
  /api/private/hello:
    get:
      consumes:
      - application/json
      description: A simple Hello World endpoint
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Says hello
      tags:
      - greetings
  /health:
    get:
      consumes:
      - application/json
      description: Check the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
